FROM python:3.10-slim

WORKDIR /app

# Installer gcc, python-dev, libpq-dev et nettoyer apt cache 
RUN apt-get update && \
    apt-get install -y gcc python3-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt


COPY Postgres/ /app/Postgres/

WORKDIR /app/Postgres

CMD ["python", "load_offers.py"]
