# Base image with Python
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends curl git python3-venv python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies

COPY skillner_requirements.txt .
RUN pip install --no-cache-dir -r  skillner_requirements.txt
RUN python -m spacy download en_core_web_lg

ENV PYTHONPATH=/app
# Copy project files into the container
COPY . .

# Default command to run the script
CMD ["python", "skillner_logic.py"]
