FROM bitnami/spark:3.3.2
USER root

# 🔧 Fix DNS issue


# 🧱 Installer les dépendances
RUN apt-get update \
    && apt-get install -y python3-psycopg2 python3-boto3 \
    && rm -rf /var/lib/apt/lists/*

USER 1001
COPY transform_job.py /opt/

ADD postgresql-42.7.3.jar /opt/bitnami/spark/jars/
CMD ["spark-submit", "/opt/transform_job.py"]
